# Generated by Django 4.1.1 on 2023-08-20 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccines', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vaccine',
            options={'verbose_name': 'Vacuna', 'verbose_name_plural': 'Vacunas'},
        ),
    ]
