# Generated by Django 4.1.1 on 2023-08-19 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0002_alter_specie_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specie',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
