# Generated by Django 4.1.1 on 2023-08-20 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sexes', '0002_alter_sex_options_rename_nombre_sex_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sex',
            name='created_at',
        ),
    ]
