# Generated by Django 4.1.1 on 2023-03-18 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_lastname_user_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('consultation', models.TextField()),
                ('pet_name', models.CharField(max_length=255)),
                ('pet_specie', models.CharField(max_length=255)),
            ],
        ),
    ]
