# Generated by Django 4.1.1 on 2023-08-18 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_preregistration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PreRegistration',
        ),
    ]
