# Generated by Django 4.1.1 on 2023-08-19 02:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pre_registration', '0003_remove_preregistration_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preregistration',
            name='created_at',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now),
        ),
    ]
