# Generated by Django 4.1.1 on 2023-08-19 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pre_registration', '0004_alter_preregistration_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preregistration',
            name='is_deleted',
        ),
    ]
