# Generated by Django 4.1.1 on 2023-08-20 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_alter_pet_options_petvaccine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='father',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='father_pets', to='pets.pet', verbose_name='padre'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='mother',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mother_pets', to='pets.pet', verbose_name='madre'),
        ),
    ]
